def months_convector(month) -> int:
    convector = {
        "січня": 1,
        "лютого": 2,
        "березня": 3,
        "квітня": 4,
        "травня": 5,
        "червня": 6,
        "липня": 7,
        "серпня": 8,
        "вересня": 9,
        "жовтня": 10,
        "листопада": 11,
        "грудня": 12,
    }

    return convector.get(month)


technologies_list = [
    "AWS",
    "Agile",
    "Airflow",
    "Algorithms",
    "Angular",
    "Ansible",
    "Azure",
    "Beautiful Soup",
    "BeeWare",
    "Black",
    "CI/CD",
    "CSS",
    "Cassandra",
    "Celery",
    "Chef",
    "CherryPy",
    "Click",
    "CloudFormation",
    "Clouds",
    "CouchDB",
    "DRF",
    "Dash",
    "Data Modeling",
    "Django",
    "Django ORM",
    "Docker",
    "DynamoDB",
    "Elasticsearch",
    "Electron",
    "Fabric",
    "Falcon",
    "FastAPI",
    "Firebase",
    "Flask",
    "Flask-RESTful",
    "Git",
    "GitLab",
    "Go",
    "Golang",
    "Google Cloud",
    "Google Cloud Platform",
    "Grafana",
    "GraphQL",
    "HTML",
    "IBM Db2",
    "JS",
    "JWT",
    "JavaScript",
    "Jenkins",
    "Jupyter Notebooks",
    "K8s",
    "Kafka",
    "Kanban",
    "Keras",
    "Kivy",
    "Kubernetes",
    "LightGBM",
    "Linux",
    "Machine learning",
    "MariaDB",
    "Marshmallow",
    "Matplotlib",
    "Microservices",
    "Microsoft SQL Server",
    "MkDocs",
    "MongoDB",
    "MySQL",
    "NLTK",
    "Neo4j",
    "Nginx",
    "NoSQL",
    "Node.js",
    "NumPy",
    "OAuth",
    "OOP",
    "Oracle Database",
    "Pandas",
    "Peewee",
    "PostgreSQL",
    "Prometheus",
    "Puppet",
    "PyQt",
    "PyTorch",
    "Pydantic",
    "Pyramid",
    "Pytest",
    "Python",
    "RBAC",
    "REST",
    "RESTful API",
    "React",
    "React Native",
    "Redis",
    "Rest API",
    "Robot Framework",
    "SQLAlchemy",
    "SQLite",
    "SQl",
    "SciPy",
    "Scikit-learn",
    "Scrapy",
    "Scrum",
    "Selenium",
    "Serverless computing",
    "Spacy",
    "Sphinx",
    "Splinter",
    "Splunk",
    "TensorFlow",
    "Terraform",
    "Tkinter",
    "Tornado",
    "Travis CI",
    "TypeScript",
    "Vue.js",
    "XGBoost",
    "async/await",
    "asyncio",
    "flake8",
    "loguru",
    "unittest",
]
